package com.gadgetbadget.user.util;

/**
 * This ENUM class contains the types of services that belongs to the GADGETBADGET web application.
 * Each service is given a unique KEY like identifier with 3 letters. These Types are included 
 * with Service JWT Tokens generated by the USER SERVICE which are then used to authenticate web 
 * services when service-to-service communication takes place.
 * 
 * @author Ishara_Dissanayake
 */
public enum ServiceType {
	USR,
	MKT,
	PYT,
	RHB,
	FND
}
