package com.gadgetbadget.user.util;

/**
 * This ENUM class contains the types of users/stake-holders that directly interacts with the 
 * GADGETBADGET web application. Each type of user is given a unique KEY like identifier with 5 
 * letters. These Types are included with Authentication JWT Tokens generated by the USER SERVICE
 * which are then used to authenticate logged-in users and to perform end-point user authorization.
 * 
 * @author Ishara_Dissanayake
 */
public enum UserType {
	ADMIN,
	EMPLY,
	FNMGR,
	RSCHR,
	FUNDR,
	CNSMR,
	INVLD
}
